In [1]:
import pandas as pd

In [2]:
import mysql.connector as connection

try:
    mydb = connection.connect(host="localhost", user = "root", passwd = "Admin@123", use_pure = True)
    query = "SHOW DATABASES"
    cursor = mydb.cursor()
    cursor.execute(query)
    print(cursor.fetchall())

except Exception as e:
    mydb.close()
    print(str(e))

[('customers',), ('information_schema',), ('lco_films',), ('lco_git_share',), ('lco_users',), ('mysql',), ('new_lco',), ('performance_schema',), ('photo_store',), ('prwatech',), ('sys',)]

In [3]:
mydb.is_connected()

True

In [4]:
query = input("Query: ")
cursor.execute(query)

Query:  use prwatech

In [5]:
cursor.execute("SET sql_mode=''")

In [6]:

query = input("Query : ")
try:
    df = pd.read_sql(query, mydb)
except Exception as e:
    mydb.close()
    print(str(e))

Query :  SELECT date, app_name, SUM(usage_seconds/60) usage_mins, SUM(usage_seconds/60)/60 usage_hrs, SUM(usage_seconds/60)/29 avg_mins_per_day FROM yourhour  GROUP BY app_name ORDER BY usage_mins DESC

/home/harshal/anaconda3/lib/python3.9/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

In [7]:
df

,date,app_name,usage_mins,usage_hrs,avg_mins_per_day
0,2022-07-19,YouTube Vanced,2038.0997,33.968328,70.279300
1,2022-07-15,Chrome,1608.5665,26.809442,55.467810
2,2022-07-21,Twitter,1426.5168,23.775280,49.190234
3,2022-07-17,Call,1298.4333,21.640555,44.773562
4,2022-07-15,PrepLadder,1008.3500,16.805833,34.770690
...,...,...,...,...,...
138,2022-07-16,Phone calls,0.0000,0.000000,0.000000
139,2022-07-15,Speech Services by Google,0.0000,0.000000,0.000000
140,2022-07-02,Smart Widget,0.0000,0.000000,0.000000
141,2022-07-03,Link to Windows Service,0.0000,0.000000,0.000000
142,2022-07-09,Key Chain,0.0000,0.000000,0.000000

In [8]:
df.to_excel('app_usage.xlsx')

In [4]:
df1 = pd.read_excel("YourHour Usage Data Sheet.xls")

In [5]:
df1

,id,date,app_name,usage_seconds,launch_count,is_monitored,is_sys_app,package_name
0,1,2022/07/15,PrepLadder,9175,32,Yes,No,com.prepladder.learningapp
1,2,2022/07/15,Gboard,1,3,Yes,No,com.google.android.inputmethod.latin
2,3,2022/07/21,Cricbuzz,256,6,Yes,No,com.cricbuzz.android
3,4,2022/07/20,Relevel,157,3,Yes,No,com.relevel
4,5,2022/07/15,Wallpaper services,1,1,No,Yes,com.samsung.android.dynamiclock
...,...,...,...,...,...,...,...,...
1288,1289,2022/07/29,FanCode,6914,24,Yes,No,com.dream11sportsguru
1289,1290,2022/07/29,Google,0,3,Yes,No,com.google.android.googlequicksearchbox
1290,1291,2022/07/29,Calculator,23,1,Yes,No,com.sec.android.app.popupcalculator
1291,1292,2022/07/29,Relevel,128,2,Yes,No,com.relevel
1292,1293,2022/07/29,Discord,236,6,Yes,No,com.discord